# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-ecs
  description: This component is responsible for provisioning an ECS Cluster and associated load balancer
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
